import React from 'react';
import { Shield, ArrowLeft } from 'lucide-react';

export default function Disclaimer({ onBack }: { onBack: () => void }) {
  return (
    <div className="min-h-screen bg-[#F8F9FB] text-[#181d1a] py-12 px-6">
      <div className="max-w-3xl mx-auto bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-slate-100">
        
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-slate-500 hover:text-[#047857] transition-colors mb-8 font-semibold text-sm"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="w-12 h-12 rounded-xl bg-orange-100 flex items-center justify-center text-orange-600">
            <Shield className="w-6 h-6" />
          </div>
          <h1 className="text-3xl font-black tracking-tight text-slate-800">Legal Disclaimer</h1>
        </div>
        
        <p className="text-slate-500 mb-8 font-medium">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="space-y-8 text-slate-600 leading-relaxed">
          
          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-3">1. Not Financial Advice</h2>
            <p>
              The information and tools provided by BantayBills are for informational and organizational purposes only. 
              <strong> BantayBills is not a registered investment, legal, or tax advisor, nor a broker/dealer.</strong> 
              No content generated by our platform—including insights generated by our AI tools—should be construed as financial, 
              investment, legal, or tax advice. You should always consult with a licensed professional before making any financial decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-3">2. Artificial Intelligence (AI) Insights</h2>
            <p>
              BantayBills utilizes Google's Gemini API to analyze your bill patterns and generate proactive financial suggestions. 
              While we strive for accuracy, AI models can occasionally produce hallucinated, inaccurate, or outdated information. 
              You must independently verify all AI-generated advice before taking action. We assume no liability for financial losses 
              incurred from relying on these automated insights.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-3">3. Data Accuracy & User Responsibility</h2>
            <p>
              BantayBills does not automatically sync or connect to your real bank accounts or utility providers via Open Banking. 
              All data within the platform is manually inputted by you (the user) or generated via demo tools. We are not responsible 
              for missed payments, late fees, or service disconnections resulting from inaccurate data entry, missed push notifications, 
              or software downtime. You are solely responsible for ensuring your bills are paid on time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-3">4. "As Is" Service</h2>
            <p>
              The BantayBills platform is provided on an "as is" and "as available" basis without any warranties, express or implied. 
              We do not guarantee that the service will be uninterrupted, error-free, or entirely secure.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
